# Generated by Django 2.1.2 on 2018-12-14 19:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eve_api', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.BigIntegerField()),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_api.ObjectType')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.TradingRoute')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='shoppinglistitem',
            index_together={('route', 'object_type')},
        ),
    ]
