# Generated by Django 2.1.2 on 2019-01-03 18:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eve_api', '0001_initial'),
        ('market', '0003_auto_20190103_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerOrderScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_start', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scan_complete', models.DateTimeField(db_index=True, default=None, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_api.EVEPlayerCharacter')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTransactionScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_start', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scan_complete', models.DateTimeField(db_index=True, default=None, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_api.EVEPlayerCharacter')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='playertransactionscanlog',
            index_together={('character', 'scan_start'), ('character', 'scan_complete')},
        ),
        migrations.AlterIndexTogether(
            name='playerorderscanlog',
            index_together={('character', 'scan_start'), ('character', 'scan_complete')},
        ),
    ]
