# Generated by Django 2.1.2 on 2019-01-14 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20190103_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingroute',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
