# Generated by Django 2.1.2 on 2019-01-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_tradingroute_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingroute',
            name='colorblind',
            field=models.BooleanField(default=False),
        ),
    ]
