# Generated by Django 2.1.2 on 2019-01-16 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eve_api', '0001_initial'),
        ('market', '0006_tradingroute_colorblind'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetContainer',
            fields=[
                ('ccp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=128, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_api.EVEPlayerCharacter')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_api.Structure')),
            ],
        ),
        migrations.CreateModel(
            name='AssetEntry',
            fields=[
                ('ccp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('quantity', models.BigIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_api.EVEPlayerCharacter')),
                ('container', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.AssetContainer')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_api.ObjectType')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_api.Structure')),
            ],
        ),
    ]
