# Generated by Django 2.1.2 on 2019-01-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20190117_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingroute',
            name='last_viewed',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
