# Generated by Django 2.1.2 on 2018-11-21 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CcpIdTypeResolver',
            fields=[
                ('ccp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(choices=[('character', 'character'), ('corporation', 'corporation'), ('alliance', 'alliance'), ('system', 'star system'), ('faction', 'faction'), ('mailing_list', 'mailing list')], max_length=250, null=True)),
            ],
            options={
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='CharacterAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_hash', models.CharField(help_text="This hash is provided by CCP to identify when a character has been transferred to another account.         Other characters on the same account will have different account hashes, so don't use this for identifying         accounts, only character xfers.", max_length=190, verbose_name='Account Owner Hash')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_login', models.DateTimeField(auto_now_add=True)),
                ('association_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterESIRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField(auto_now=True)),
                ('esi_alliances_read_contacts_v1', models.BooleanField(default=False)),
                ('esi_assets_read_assets_v1', models.BooleanField(default=False)),
                ('esi_assets_read_corporation_assets_v1', models.BooleanField(default=False)),
                ('esi_bookmarks_read_character_bookmarks_v1', models.BooleanField(default=False)),
                ('esi_bookmarks_read_corporation_bookmarks_v1', models.BooleanField(default=False)),
                ('esi_calendar_read_calendar_events_v1', models.BooleanField(default=False)),
                ('esi_calendar_respond_calendar_events_v1', models.BooleanField(default=False)),
                ('esi_characters_read_agents_research_v1', models.BooleanField(default=False)),
                ('esi_characters_read_blueprints_v1', models.BooleanField(default=False)),
                ('esi_characters_read_contacts_v1', models.BooleanField(default=False)),
                ('esi_characters_read_corporation_roles_v1', models.BooleanField(default=False)),
                ('esi_characters_read_fatigue_v1', models.BooleanField(default=False)),
                ('esi_characters_read_fw_stats_v1', models.BooleanField(default=False)),
                ('esi_characters_read_loyalty_v1', models.BooleanField(default=False)),
                ('esi_characters_read_medals_v1', models.BooleanField(default=False)),
                ('esi_characters_read_notifications_v1', models.BooleanField(default=False)),
                ('esi_characters_read_opportunities_v1', models.BooleanField(default=False)),
                ('esi_characters_read_standings_v1', models.BooleanField(default=False)),
                ('esi_characters_read_titles_v1', models.BooleanField(default=False)),
                ('esi_characters_write_contacts_v1', models.BooleanField(default=False)),
                ('esi_characterstats_read_v1', models.BooleanField(default=False)),
                ('esi_clones_read_clones_v1', models.BooleanField(default=False)),
                ('esi_clones_read_implants_v1', models.BooleanField(default=False)),
                ('esi_contracts_read_character_contracts_v1', models.BooleanField(default=False)),
                ('esi_contracts_read_corporation_contracts_v1', models.BooleanField(default=False)),
                ('esi_corporations_read_blueprints_v1', models.BooleanField(default=False)),
                ('esi_corporations_read_contacts_v1', models.BooleanField(default=False)),
                ('esi_corporations_read_container_logs_v1', models.BooleanField(default=False)),
                ('esi_corporations_read_corporation_membership_v1', models.BooleanField(default=False)),
                ('esi_corporations_read_divisions_v1', models.BooleanField(default=False)),
                ('esi_corporations_read_facilities_v1', models.BooleanField(default=False)),
                ('esi_corporations_read_fw_stats_v1', models.BooleanField(default=False)),
                ('esi_corporations_read_medals_v1', models.BooleanField(default=False)),
                ('esi_corporations_read_outposts_v1', models.BooleanField(default=False)),
                ('esi_corporations_read_standings_v1', models.BooleanField(default=False)),
                ('esi_corporations_read_starbases_v1', models.BooleanField(default=False)),
                ('esi_corporations_read_structures_v1', models.BooleanField(default=False)),
                ('esi_corporations_read_titles_v1', models.BooleanField(default=False)),
                ('esi_corporations_track_members_v1', models.BooleanField(default=False)),
                ('esi_fittings_read_fittings_v1', models.BooleanField(default=False)),
                ('esi_fittings_write_fittings_v1', models.BooleanField(default=False)),
                ('esi_fleets_read_fleet_v1', models.BooleanField(default=False)),
                ('esi_fleets_write_fleet_v1', models.BooleanField(default=False)),
                ('esi_industry_read_character_jobs_v1', models.BooleanField(default=False)),
                ('esi_industry_read_character_mining_v1', models.BooleanField(default=False)),
                ('esi_industry_read_corporation_jobs_v1', models.BooleanField(default=False)),
                ('esi_industry_read_corporation_mining_v1', models.BooleanField(default=False)),
                ('esi_killmails_read_corporation_killmails_v1', models.BooleanField(default=False)),
                ('esi_killmails_read_killmails_v1', models.BooleanField(default=False)),
                ('esi_location_read_location_v1', models.BooleanField(default=False)),
                ('esi_location_read_online_v1', models.BooleanField(default=False)),
                ('esi_location_read_ship_type_v1', models.BooleanField(default=False)),
                ('esi_mail_organize_mail_v1', models.BooleanField(default=False)),
                ('esi_mail_read_mail_v1', models.BooleanField(default=False)),
                ('esi_mail_send_mail_v1', models.BooleanField(default=False)),
                ('esi_markets_read_character_orders_v1', models.BooleanField(default=False)),
                ('esi_markets_read_corporation_orders_v1', models.BooleanField(default=False)),
                ('esi_markets_structure_markets_v1', models.BooleanField(default=False)),
                ('esi_planets_manage_planets_v1', models.BooleanField(default=False)),
                ('esi_planets_read_customs_offices_v1', models.BooleanField(default=False)),
                ('esi_search_search_structures_v1', models.BooleanField(default=False)),
                ('esi_skills_read_skillqueue_v1', models.BooleanField(default=False)),
                ('esi_skills_read_skills_v1', models.BooleanField(default=False)),
                ('esi_ui_open_window_v1', models.BooleanField(default=False)),
                ('esi_ui_write_waypoint_v1', models.BooleanField(default=False)),
                ('esi_universe_read_structures_v1', models.BooleanField(default=False)),
                ('esi_wallet_read_character_wallet_v1', models.BooleanField(default=False)),
                ('esi_wallet_read_corporation_wallets_v1', models.BooleanField(default=False)),
                ('esi_characters_read_chat_channels_v1', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('ccp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='EsiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(default=None, max_length=512, null=True, verbose_name='ESI Refresh Token/Key')),
                ('esi_key_last_validated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date ESI key Last Validated')),
                ('esi_key_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date ESI key Added')),
                ('owner_hash', models.CharField(default=None, help_text="This hash is provided by CCP to identify when a character has been transferred to another account.         Other characters on the same account will have different account hashes, so don't use this for identifying         accounts, only character xfers.", max_length=190, null=True, verbose_name='Account Owner Hash')),
                ('use_key', models.BooleanField(default=True)),
                ('_esi_roles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eve_api.CharacterESIRoles')),
            ],
        ),
        migrations.CreateModel(
            name='EVEPlayerAlliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('ticker', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'verbose_name': 'Alliance',
                'verbose_name_plural': 'Alliances',
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='EVEPlayerCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('orders_last_updated', models.DateTimeField(default=None, null=True)),
                ('assets_last_updated', models.DateTimeField(default=None, null=True)),
                ('transactions_last_updated', models.DateTimeField(default=None, null=True)),
                ('journal_last_updated', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='EVEPlayerCorporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('ticker', models.CharField(blank=True, max_length=15, null=True)),
                ('alliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eve_api.EVEPlayerAlliance')),
            ],
            options={
                'verbose_name': 'Corporation',
                'verbose_name_plural': 'Corporations',
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('ccp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_unique', models.BooleanField()),
                ('size_factor', models.FloatField()),
            ],
            options={
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('ccp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('parent_container', models.BigIntegerField(default=None, null=True)),
                ('root_location_id', models.BigIntegerField(db_index=True, default=None)),
                ('is_in_space', models.BooleanField(default=False)),
                ('constellation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eve_api.Constellation')),
            ],
            options={
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='MarketGroup',
            fields=[
                ('ccp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.BigIntegerField(default=None, null=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('ccp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('volume', models.BigIntegerField(default=None, null=True)),
                ('packaged_volume', models.FloatField(default=None, null=True)),
                ('icon_id', models.BigIntegerField()),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('ccp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('ccp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('is_blank', models.BooleanField(default=False)),
                ('market_last_updated', models.DateTimeField(default=None, null=True)),
                ('market_data_expires', models.DateTimeField(default=None, null=True)),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eve_api.Location')),
                ('type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eve_api.ObjectType')),
            ],
            options={
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('ccp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('security_status', models.FloatField()),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_api.Constellation')),
            ],
            options={
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='TypeCategory',
            fields=[
                ('ccp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='TypeGroup',
            fields=[
                ('ccp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_api.TypeCategory')),
            ],
            options={
                'select_on_save': True,
            },
        ),
        migrations.AddField(
            model_name='objecttype',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eve_api.TypeGroup'),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='market_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eve_api.MarketGroup'),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eve_api.Region'),
        ),
        migrations.AddField(
            model_name='location',
            name='system',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eve_api.System'),
        ),
        migrations.AddField(
            model_name='eveplayercharacter',
            name='corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eve_api.EVEPlayerCorporation'),
        ),
        migrations.AddField(
            model_name='esikey',
            name='character',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key', to='eve_api.EVEPlayerCharacter', verbose_name='Character'),
        ),
        migrations.AddField(
            model_name='esikey',
            name='owner',
            field=models.ForeignKey(default=None, help_text='User who created this ESI key', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esi_key_creator', to=settings.AUTH_USER_MODEL, verbose_name='Key Creator'),
        ),
        migrations.AddField(
            model_name='constellation',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_api.Region'),
        ),
        migrations.AddField(
            model_name='characteresiroles',
            name='key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eve_api.EsiKey'),
        ),
        migrations.AddField(
            model_name='characterassociation',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_api.EVEPlayerCharacter', verbose_name='Character'),
        ),
        migrations.AddField(
            model_name='characterassociation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='objecttype',
            index_together={('market_group', 'published')},
        ),
        migrations.AlterIndexTogether(
            name='characterassociation',
            index_together={('character', 'owner_hash', 'association_active')},
        ),
    ]
