# Generated by Django 2.1.2 on 2018-12-18 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eve_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trial_payment', models.BooleanField(default=False)),
                ('amount', models.BigIntegerField()),
                ('journal_id', models.BigIntegerField(db_index=True, default=0)),
                ('payment_time_actual', models.DateTimeField()),
                ('payment_read_time', models.DateTimeField(auto_now_add=True)),
                ('source_character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eve_api.EVEPlayerCharacter')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('credit_remaining', models.BigIntegerField(default=0)),
                ('credit_consumed', models.BigIntegerField(default=0)),
                ('subscription_last_updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.SubscriptionStatus'),
        ),
    ]
