# Generated by Django 2.1.2 on 2018-12-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='journal_id',
            field=models.BigIntegerField(db_index=True, default=0, unique=True),
        ),
    ]
