# Generated by Django 2.1.2 on 2018-12-19 23:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20181219_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_read_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 19, 23, 32, 52, 579324, tzinfo=utc)),
        ),
    ]
