# Generated by Django 2.1.2 on 2018-12-19 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20181219_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_read_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
