# Generated by Django 2.1.2 on 2018-12-19 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20181219_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_time_actual',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
