# Generated by Django 2.1.2 on 2019-01-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20181219_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionstatus',
            name='subscription_last_updated',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
